version: '3'

services:
  my-backend:
    build: ./node-app
    volumes:
      - ./node-app:/backend
      - node_modules:/backend/node_modules/
    ports:
      - 8080:80
      
  my-frontend:
    build: ./react-app
    volumes:
      - ./react-app:/frontend
      - node_modules:/frontend/node_modules/
    ports:
      - 3000:3000
    depends_on:
      - my-backend
volumes:
  node_modules: